// Harvest Festival
// The stem is represented by hyphens -, and the flowers are represented by symbols. A plant always starts with the stem, and always ends with flowers.
// Four parameters will be given. The four parameters are:
// seed (string) - determines the type of flowers generated by the plant.
// water (integer) - each unit of water extends the portion of stem between the flowers. It also gives how many times the stems + flower clusters should be repeated
// fert (integer) - each unit of fertilizer increases the amount of flowers, grouped in clusters
// temp (integer) - if the temperature given is in the range of 20°C and 30°C, the plant grows normally, otherwise, all the flowers die except for one flower at the end of the stem.

function plant(seed, water, fert, temp) {
  //your code here
  if (temp >= 20 && temp <= 30) {
    return "-".repeat(water).concat(seed.repeat(fert)).repeat(water);
  } else {
    return "-".repeat(water).repeat(water).concat(seed);
  }
}
